import type { Metadata } from "next";
import Link from "next/link";
import { DocumentPage } from "@/components/site";
export const metadata: Metadata = { title: "Cookies", description: "Cookies, browser storage, and tracking on the Pins website.", alternates: { canonical: "/cookies/" } };
export default function Cookies() {
  return <DocumentPage label="BROWSER PRIVACY" title="Cookies & storage." intro="The current website does not set its own cookies or use localStorage or sessionStorage. It has no optional analytics or advertising trackers." updated>
    <section><h2>What cookies and storage do</h2><p>Cookies are small pieces of information a site can ask your browser to keep and send with later requests. Local and session storage can save information in your browser without sending it automatically. They can support sign-in or preferences, but can also be used for tracking.</p></section>
    <section><h2>What this website uses</h2><p>The website has no sign-in session, cookie-based preferences, tracking pixels, embedded media, or consent record. Fonts and images are served from the website itself. There is no third-party map behind the illustrated preview.</p><p>Your browser may cache page files, images, and fonts so they load faster. This is ordinary browser caching, not an analytics identifier added by Pins.</p></section>
    <section><h2>Email-confirmation pages</h2><p>The confirmation page reads result information from its URL and clears recognized credentials and raw error details after loading. It does not save those values in cookies or local or session storage. Browser history and server request logs are different from cookies: URL query strings may reach the host before cleanup. See <Link href="/privacy">Privacy</Link> for more detail.</p><p>The documented Supabase email-verification step happens before you arrive at this website. This site does not initialize Supabase authentication or its session storage.</p></section>
    <section><h2>Why there is no consent banner</h2><p>The current website includes no optional tracking or storage to accept or reject, so there is no cookie-consent banner or preference to save. If optional technologies are introduced, this page and the controls offered to visitors will need to change before those technologies are used.</p><p>Hosting infrastructure may handle operational requests separately from the website code. A hosting or service change can affect browser behavior and must be reviewed.</p></section>
    <section><h2>Your controls</h2><p>You can inspect, block, or clear site data in your browser’s privacy settings. No account or cookie permission is needed to read these policies. Clearing browser data does not delete a Pins app account or email correspondence.</p><p>For help with personal information, visit <Link href="/data-request">Data Requests</Link>.</p></section>
  </DocumentPage>;
}
