import type { Metadata } from "next";
import Link from "next/link";
import { DocumentPage } from "@/components/site";
import { emailHref, supportEmail } from "@/lib/site-config";
export const metadata: Metadata = { title: "Data Requests", description: "Request account deletion, deletion of personal data, access, correction, or help with privacy at Pins.", alternates: { canonical: "/data-request/" } };
export default function DataRequest() {
  const href = emailHref("Pins privacy request");
  return <DocumentPage label="YOUR INFORMATION" title="Make a data request." intro="Account deletion, a copy of your information, or a question about privacy. Here is what to include and what a request means." updated>
    <section><h2>What you can ask for</h2><div className="request-grid"><article className="request-card"><h3>Account & data deletion</h3><p>Ask to delete your account or associated personal information. Specify if you only want particular information removed.</p></article><article className="request-card"><h3>Access to information</h3><p>Ask about personal information associated with your account or correspondence.</p></article><article className="request-card"><h3>Corrections & updates</h3><p>Tell us what information needs correcting and the change you are requesting.</p></article><article className="request-card"><h3>Other privacy questions</h3><p>Ask about sharing, information handling, or another privacy right that applies to you.</p></article></div></section>
    <section><h2>Send your request by email</h2><div className="info-card"><p>Use the email associated with your Pins account when possible. Sending from another address is also possible; explain if you have lost access.</p><a className="button primary" href={href}>Email a privacy request</a><p>Opens your email app. You must send the message yourself. You can also write directly to <a href={emailHref()}>{supportEmail}</a>.</p></div><p>Include the request type and the account email or username needed to identify the account. If you are writing about website correspondence rather than an account, describe that correspondence. A full legal name, postal address, date of birth, phone number, and identity document are not requested here.</p><p>Do not send passwords, confirmation links, sign-in codes, or unrelated sensitive information. See <Link href="/privacy">Privacy</Link> for how request information is handled.</p></section>
    <section><h2>After a request is sent</h2><p>An email is a request for review, not confirmation that an account or its data has been deleted. Account ownership may need to be verified before information is disclosed, changed, or removed. The outcome depends on the request, the information involved, and applicable requirements; this page does not promise an immediate result or a specific response time.</p><p>Some records may need to be retained for legal or security reasons, and copies shared with others may remain outside Pins’ control. Ask about the scope of deletion if you are unsure what will be affected.</p></section>
    <section><h2>Account deletion in the app</h2><p>The existing app guidance points to Profile → Settings → Delete Account. Availability can depend on your beta version. Read <Link href="/delete-account">account deletion guidance</Link> before confirming a permanent action. Uninstalling the app does not delete an account.</p></section>
  </DocumentPage>;
}
