import { Icon } from "@/components/icons";
import { PhonePreview } from "@/components/map-preview";
import Link from "next/link";
import { emailHref } from "@/lib/site-config";
export const metadata = { alternates: { canonical: "/" } };
export default function Home() { const notifyHref = emailHref("Pins beta availability"); return <main id="main-content" tabIndex={-1}>
  <section className="hero shell"><div className="hero-copy"><div className="beta-badge"><span/> A new way to keep your world close</div><h1>Save places.<br/>Share maps.<br/><span>Discover<br className="desktop-break"/> your world.</span></h1><p>Pins is a social map for saving places, sharing private Circles with friends, and discovering public maps from people you trust.</p><div className="hero-actions"><a href="#coming-soon" className="button primary">Coming soon to iPhone <Icon name="arrow" size={17}/></a><a href="#features" className="text-link">Meet Pins <Icon name="arrow" size={17}/></a></div><div className="hero-footnote"><span className="tiny-pin"><Icon name="pin" size={14}/></span> Your places. Your people. All in one map.</div></div><PhonePreview/></section>
  <section id="features" className="features shell"><div className="section-heading"><p className="eyebrow">LESS SEARCHING. MORE LIVING.</p><h2>Your world, a little closer.</h2><p>For the places you love. And the ones you haven’t found yet.</p></div><div className="feature-grid">
    <article className="feature-card"><div className="feature-visual saved-visual" aria-hidden="true"><div className="saved-item"><span><Icon name="coffee"/></span><div>Saturday coffee<small>Somewhere to slow down</small></div><Icon name="bookmark" size={17}/></div><div className="saved-item second"><span><Icon name="pin"/></span><div>Next weekend<small>A little out of the way</small></div><Icon name="bookmark" size={17}/></div></div><div className="feature-copy"><span className="feature-label"><Icon name="bookmark" size={16}/> SAVE PLACES</span><h3>Save every place<br/>worth keeping.</h3><p>Restaurants, study spots, trip ideas, date spots, coffee shops, and anything you want to remember.</p></div></article>
    <article className="feature-card"><div className="feature-visual circles-visual" aria-hidden="true"><div className="circle-ring ring-outer"/><div className="circle-ring ring-inner"/><span className="circle-center"><Icon name="pin" size={30}/></span><span className="circle-person person-a">J</span><span className="circle-person person-b">A</span><span className="circle-person person-c">M</span><span className="private-label"><Icon name="lock" size={12}/> Just us</span></div><div className="feature-copy"><span className="feature-label"><Icon name="people" size={16}/> SHARE WITH CIRCLES</span><h3>Private maps<br/>for your people.</h3><p>Create Circles for friends, trips, campuses, or groups. Choose a Circle for the places you want to share with that group.</p></div></article>
    <article className="feature-card"><div className="feature-visual discover-visual" aria-hidden="true"><div className="mini-map"><div className="mini-road"/><span className="mini-map-pin"><Icon name="pin" size={22}/></span><div className="mini-map-caption"><span className="creator-avatar">A</span><div>A slow Sunday<small>A public map to explore</small></div><Icon name="arrow" size={15}/></div></div></div><div className="feature-copy"><span className="feature-label"><Icon name="compass" size={16}/> DISCOVER PUBLIC MAPS</span><h3>Find places<br/>through people.</h3><p>Follow friends and creators, explore their public maps, and save the spots you like to your own map.</p></div></article>
    <article className="feature-card"><div className="feature-visual privacy-visual" aria-hidden="true"><div className="visibility-row active"><Icon name="lock" size={17}/><span>Only me</span><span className="radio-check"><Icon name="check" size={11}/></span></div><div className="visibility-row"><Icon name="people" size={17}/><span>My Circles</span><span className="radio"/></div><div className="visibility-row"><Icon name="compass" size={17}/><span>Everyone</span><span className="radio"/></div></div><div className="feature-copy"><span className="feature-label"><Icon name="lock" size={16}/> KEEP CONTROL</span><h3>Choose how<br/>you share.</h3><p>Keep places for yourself, share with a Circle, or build a public map. Check the audience before you share.</p></div></article>
  </div></section>
  <section id="coming-soon" className="coming-soon shell"><div className="coming-inner"><span className="coming-icon"><Icon name="pin" size={30}/></span><p className="eyebrow">GOOD PLACES ARE JUST THE BEGINNING</p><h2>Built for people who save<br/>places everywhere.</h2><p>Pins is preparing for beta testing. Follow along as we get<br className="desktop-break"/> ready for TestFlight and the App Store.</p>{notifyHref ? <><a className="button primary" href={notifyHref}>Ask about beta access <Icon name="arrow" size={17}/></a><small>Opens your email app. Send your question to ask about availability; this does not subscribe you to marketing. <Link href="/privacy">Privacy</Link></small></> : <><Link className="button primary" href="/support">Visit support <Icon name="arrow" size={17}/></Link><small>Beta invitations and App Store downloads are not available here yet.</small></>}<span className="coming-contour contour-one"/><span className="coming-contour contour-two"/></div></section>
</main>; }
