import { Icon } from "@/components/icons";
import { FeatureScreenshot, PhonePreview } from "@/components/app-screens";
import Link from "next/link";
import { betaAccessHref } from "@/lib/site-config";
import homeCategories from "@/assets/app/home-categories.webp";
import circles from "@/assets/app/circles.webp";
import explore from "@/assets/app/explore.webp";
export const metadata = { alternates: { canonical: "/" } };
export default function Home() { return <main id="main-content" tabIndex={-1}>
  <section className="hero shell"><div className="hero-copy"><div className="beta-badge"><span/> A new way to keep your world close</div><h1>Save places.<br/>Share maps.<br/><span>Discover<br className="desktop-break"/> your world.</span></h1><p>Pins is a social map for saving places, sharing private Circles with friends, and discovering public maps from people you trust.</p><div className="hero-actions"><a href="#coming-soon" className="button primary">Coming soon to iPhone <Icon name="arrow" size={17}/></a><a href="#features" className="text-link">Meet Pins <Icon name="arrow" size={17}/></a></div><div className="hero-footnote"><span className="tiny-pin"><Icon name="pin" size={14}/></span> Your places. Your people. All in one map.</div></div><PhonePreview/></section>
  <section id="features" className="features shell"><div className="section-heading"><p className="eyebrow">LESS SEARCHING. MORE LIVING.</p><h2>Your world, a little closer.</h2><p>For the places you love. And the ones you haven’t found yet.</p></div><div className="feature-grid">
    <article className="feature-card"><FeatureScreenshot src={homeCategories} alt="Pins Home map with a place search bar and category filters for food, coffee, books, shopping, and more above color-coded saved pins."/><div className="feature-copy"><span className="feature-label"><Icon name="bookmark" size={16}/> SAVE PLACES</span><h3>Save every place{" "}<br/>worth keeping.</h3><p>Restaurants, study spots, trip ideas, date spots, coffee shops, and anything you want to remember.</p></div></article>
    <article className="feature-card"><FeatureScreenshot src={circles} alt="A Pins Circle called Walnut with 4 members and a shared map, where each pin shows the photo of the member who added it."/><div className="feature-copy"><span className="feature-label"><Icon name="people" size={16}/> SHARE WITH CIRCLES</span><h3>Private maps{" "}<br/>for your people.</h3><p>Create Circles for friends, trips, campuses, or groups. Choose a Circle for the places you want to share with that group.</p></div></article>
    <article className="feature-card"><FeatureScreenshot src={explore} alt="Pins Explore screen listing people’s public maps, each with View public map and Follow buttons."/><div className="feature-copy"><span className="feature-label"><Icon name="compass" size={16}/> DISCOVER PUBLIC MAPS</span><h3>Find places{" "}<br/>through people.</h3><p>Follow friends and creators, explore their public maps, and save the spots you like to your own map.</p></div></article>
    <article className="feature-card"><div className="feature-visual scope-visual" aria-hidden="true"><span className="scope scope-public"><span className="scope-badge"><Icon name="compass" size={15}/></span></span><span className="scope scope-circle"><span className="scope-badge"><Icon name="people" size={15}/></span></span><span className="scope scope-you"><Icon name="lock" size={22}/></span></div><div className="feature-copy"><span className="feature-label"><Icon name="lock" size={16}/> KEEP CONTROL</span><h3>Choose how{" "}<br/>you share.</h3><p>Keep places for yourself, share with a Circle, or build a public map. Check the audience before you share.</p></div></article>
  </div></section>
  <section id="coming-soon" className="coming-soon shell"><div className="coming-inner"><span className="coming-icon"><Icon name="pin" size={30}/></span><p className="eyebrow">GOOD PLACES ARE JUST THE BEGINNING</p><h2>Built for people who save<br/>places everywhere.</h2><p>Pins is preparing for beta testing. Follow along as we get<br className="desktop-break"/> ready for TestFlight and the App Store.</p><a className="button primary" href={betaAccessHref}>Ask about beta access <Icon name="arrow" size={17}/></a><small>Opens your email app. Send your question to ask about availability; this does not subscribe you to marketing. <Link href="/privacy">Privacy</Link></small><span className="coming-contour contour-one"/><span className="coming-contour contour-two"/></div></section>
</main>; }
