import { Icon } from "@/components/icons";
import { PhonePreview } from "@/components/map-preview";
import { notifyHref } from "@/components/site";
export const metadata = { alternates: { canonical: "/" } };
export default function Home() { return <main id="main-content">
  <section className="hero shell"><div className="hero-copy"><div className="beta-badge"><span/> A new way to keep your world close</div><h1>Save places.<br/>Share maps.<br/><span>Discover<br className="desktop-break"/> your world.</span></h1><p>Pins is a social map for saving places, sharing private Circles with friends, and discovering public maps from people you trust.</p><div className="hero-actions"><a href="#coming-soon" className="button primary"><svg aria-hidden="true" width="20" height="23" viewBox="0 0 24 28" fill="currentColor"><path d="M17 4c1-1 1.5-2.5 1.3-4-1.5.1-3 1-4 2-1 1.1-1.6 2.5-1.4 4 1.6.1 3-1 4.1-2ZM21.3 15c0-3 2.4-4.4 2.5-4.5-1.4-2.1-3.6-2.4-4.4-2.4-1.9-.2-3.7 1.1-4.7 1.1-1 0-2.5-1.1-4.1-1-2.1 0-4 1.2-5 3-2.2 3.8-.6 9.4 1.5 12.4 1 1.5 2.1 3.1 3.7 3 1.5 0 2.1-1 4-1s2.4 1 4.1 1c1.7 0 2.7-1.5 3.7-3 1.2-1.7 1.7-3.4 1.7-3.5-.1 0-3-1.1-3-5.1Z" transform="translate(-2 0)"/></svg><span>App Store <span className="button-sub">— Coming Soon</span></span></a><a href="#coming-soon" className="text-link">Get notified <Icon name="arrow" size={17}/></a></div><div className="hero-footnote"><span className="tiny-pin"><Icon name="pin" size={14}/></span> Your places. Your people. All in one map.</div></div><PhonePreview/></section>
  <section id="features" className="features shell"><div className="section-heading"><p className="eyebrow">LESS SEARCHING. MORE LIVING.</p><h2>Your world, a little closer.</h2><p>For the places you love. And the ones you haven’t found yet.</p></div><div className="feature-grid">
    <article className="feature-card"><div className="feature-visual saved-visual" aria-hidden="true"><div className="saved-item"><span><Icon name="coffee"/></span><div>Saturday coffee<small>Somewhere to slow down</small></div><Icon name="bookmark" size={17}/></div><div className="saved-item second"><span><Icon name="pin"/></span><div>Next weekend<small>A little out of the way</small></div><Icon name="bookmark" size={17}/></div></div><div className="feature-copy"><span className="feature-label"><Icon name="bookmark" size={16}/> SAVE PLACES</span><h3>Save every place<br/>worth keeping.</h3><p>Restaurants, study spots, trip ideas, date spots, coffee shops, and anything you want to remember.</p></div></article>
    <article className="feature-card"><div className="feature-visual circles-visual" aria-hidden="true"><div className="circle-ring ring-outer"/><div className="circle-ring ring-inner"/><span className="circle-center"><Icon name="pin" size={30}/></span><span className="circle-person person-a">J</span><span className="circle-person person-b">A</span><span className="circle-person person-c">M</span><span className="private-label"><Icon name="lock" size={12}/> Just us</span></div><div className="feature-copy"><span className="feature-label"><Icon name="people" size={16}/> SHARE WITH CIRCLES</span><h3>Private maps<br/>for your people.</h3><p>Create Circles for friends, trips, campuses, or groups. Circle maps stay private to members.</p></div></article>
    <article className="feature-card"><div className="feature-visual discover-visual" aria-hidden="true"><div className="mini-map"><div className="mini-road"/><span className="mini-map-pin"><Icon name="pin" size={22}/></span><div className="mini-map-caption"><span className="creator-avatar">A</span><div>A slow Sunday<small>A public map to explore</small></div><Icon name="arrow" size={15}/></div></div></div><div className="feature-copy"><span className="feature-label"><Icon name="compass" size={16}/> DISCOVER PUBLIC MAPS</span><h3>Find places<br/>through people.</h3><p>Follow friends and creators, explore their public maps, and save the spots you like to your own map.</p></div></article>
    <article className="feature-card"><div className="feature-visual privacy-visual" aria-hidden="true"><div className="visibility-row active"><Icon name="lock" size={17}/><span>Only me</span><span className="radio-check"><Icon name="check" size={11}/></span></div><div className="visibility-row"><Icon name="people" size={17}/><span>My Circles</span><span className="radio"/></div><div className="visibility-row"><Icon name="compass" size={17}/><span>Everyone</span><span className="radio"/></div></div><div className="feature-copy"><span className="feature-label"><Icon name="lock" size={16}/> KEEP CONTROL</span><h3>Private<br/>by default.</h3><p>Your pins start private. You choose what to keep personal, share with Circles, or make public.</p></div></article>
  </div></section>
  <section id="coming-soon" className="coming-soon shell"><div className="coming-inner"><span className="coming-icon"><Icon name="pin" size={30}/></span><p className="eyebrow">GOOD PLACES ARE JUST THE BEGINNING</p><h2>Built for people who save<br/>places everywhere.</h2><p>Pins is preparing for beta testing. Follow along as we get<br className="desktop-break"/> ready for TestFlight and the App Store.</p><a className="button primary" href={notifyHref}>Get notified <Icon name="arrow" size={17}/></a><small>Opens your email app to request beta updates.</small><span className="coming-contour contour-one"/><span className="coming-contour contour-two"/></div></section>
</main>; }
