import type { Metadata } from "next";
import Link from "next/link";
import { ContactDetails, DocumentPage } from "@/components/site";
export const metadata: Metadata = { title: "Terms", description: "Terms for the Pins website and responsible use of Pins places and sharing features.", alternates: { canonical: "/terms/" } };
export default function Terms() {
  return <DocumentPage label="USING PINS" title="Terms of use." intro="Please read these terms when using the Pins website. Pins is preparing for beta testing; access to app features depends on their availability." updated contents={[{id:"using-pins",label:"Using Pins"},{id:"content",label:"Content & sharing"},{id:"availability",label:"Availability & responsibility"}]}>
    <section id="using-pins"><h2>Scope and acceptance</h2><p>These terms describe use of this website and the responsibilities associated with Pins features when made available to you. By using the website, you agree to these terms to the extent permitted by applicable law. If you do not agree, stop using it. Any additional terms presented for a particular beta or service apply to that participation.</p><p>The website provides product information and help. It does not create an account, sell a subscription, or provide access to a live map. Illustrations are examples, and coming-soon language does not promise a release date.</p></section>
    <section><h2>Eligibility and accounts</h2><p>Use Pins only where you are legally permitted to do so and can meet any eligibility requirements presented when accessing the app. This website does not verify age or obtain parental consent.</p><p>If you have a Pins account, provide accurate information and protect your login details. Do not share passwords or confirmation codes, impersonate another person, or use another person’s account without authorization. Contact support if you suspect unauthorized use. Reading this website does not require an account.</p></section>
    <section><h2>Acceptable use</h2><p>Do not use Pins to break the law, harass or threaten people, expose someone’s private location, infringe intellectual-property rights, distribute malicious content, send spam, or attempt unauthorized access. Do not interfere with the service or bypass another person’s privacy settings.</p><p>Respect people and places. A saved Pin is not permission to enter private property, ignore local restrictions, or approach another person.</p></section>
    <section id="content"><h2>Your content and sharing choices</h2><p>You retain ownership of content you submit. You are responsible for having the rights and permission to share it. When you submit content to Pins, you give Pins permission to store, process, reproduce, and display it as needed to provide the service according to your sharing choices. This does not transfer ownership of your content.</p><p>This permission lasts while the content is needed to provide those functions, subject to deletion handling, backups, and applicable legal requirements. It does not undo copies that other people have already made.</p><p>Check who can see a Pin, map, or profile before sharing. Public content may be viewed or copied by others; content shared with a group may be retained by its members. Avoid posting sensitive details about yourself or other people.</p></section>
    <section><h2>Places, maps, and third-party content</h2><p>Place details and user-created maps can be incomplete, outdated, or inaccurate. Check opening hours, directions, access conditions, and suitability independently. Pins is not an emergency service or a guarantee that a place is safe.</p><p>Third-party links and services are subject to their own terms and privacy practices. Mentioning a place or linking to another service is not an endorsement. Pins does not control their availability or content.</p></section>
    <section><h2>Pins materials</h2><p>The Pins name, branding, and website materials are protected by applicable intellectual-property laws. Do not misrepresent affiliation with Pins or reuse materials in a way that infringes rights. Third-party materials remain subject to their own licenses, including the open-source font bundled with this website.</p></section>
    <section id="availability"><h2>Availability and changes</h2><p>Features may change, be interrupted, or be discontinued. We do not promise uninterrupted availability or that beta features will be released on a particular date. Save your own copy of information that matters to you.</p><p>Access to Pins may be restricted or suspended to address misuse, security concerns, violations of these terms, or legal requirements. You can stop using the service and request account deletion through <Link href="/data-request">Data Requests</Link>.</p></section>
    <section><h2>Disclaimers and responsibility</h2><p>To the extent permitted by applicable law, the website and available beta features are provided as available, without a promise that every feature or item of content will be accurate, uninterrupted, or suitable for your needs.</p><p>Pins is not responsible for losses caused solely by third-party services, inaccurate user-submitted place information, or your use that violates these terms, except where applicable law provides otherwise. Nothing in these terms excludes liability that cannot lawfully be excluded, or limits mandatory consumer rights. No fixed liability cap or mandatory arbitration requirement is imposed here.</p></section>
    <section><h2>Privacy, updates, and contact</h2><p>Read <Link href="/privacy">Privacy</Link> and <Link href="/cookies">Cookies</Link> for information practices. Terms may change as the website and service develop; the revision date is shown above. Changes do not remove rights already granted by applicable law.</p><p>For a question about these terms: <ContactDetails subject="Pins terms question" /></p></section>
  </DocumentPage>;
}
