import type { Metadata } from "next";
import Link from "next/link";
import { ContactDetails, DocumentPage } from "@/components/site";
export const metadata: Metadata = { title: "Privacy", description: "Information handled by the Pins website, your choices, and how to make a privacy request.", alternates: { canonical: "/privacy/" } };
export default function Privacy() {
  return <DocumentPage label="PRIVACY AT PINS" title="Your information, explained." intro="This policy explains the current Pins website at joinpins.app and its connection to the Pins app. You can read the website without creating an account." updated contents={[{id:"website",label:"Website information"},{id:"app",label:"Places & sharing"},{id:"providers",label:"Services & retention"},{id:"choices",label:"Your choices"}]}>
    <section id="website"><h2>Information on this website</h2><p>This is a public information and support website. It has no account-registration form, login form, payment form, uploads, or database for collecting requests. Browsing it does not create a Pins account.</p><p>To deliver a page, the hosting infrastructure receives request information such as your IP address, requested URL, and browser headers. The deployed host may keep operational or security logs. This website does not add analytics, advertising pixels, session replay, or fingerprinting.</p><p>The site does not request your device location, search for real places, or send map coordinates to a mapping service. The map and app screens shown here are illustrations.</p></section>
    <section><h2>Messages you choose to send</h2><p>If you email Pins, your email service and the receiving mailbox process your email address, message, and any attachments. Messages are used to address the support, beta-availability, or privacy question you send. Sending a support or privacy request is not a marketing signup.</p><p>Include only the information needed for your question. Do not send passwords, sign-in codes, identity documents, or unrelated private locations. Device and app-version details can help with a technical problem but are not needed for every request.</p></section>
    <section><h2>Email-confirmation links</h2><p>The email-confirmation page reads the result information in its URL to show guidance. It does not verify your email, sign you in, exchange a token, or create a website session. Recognized credentials and raw error details are removed from the address bar after the page loads; they are not saved in browser storage or forwarded to an app.</p><p>URL query parameters reach the hosting infrastructure before the page can clear them. Fragments (the part after a #) are processed in your browser. Do not paste confirmation links or credentials into support messages.</p></section>
    <section id="app"><h2>Places and sharing in the Pins app</h2><p>Pins is being developed for saving places and sharing maps, including Circles and public maps. Account and profile information, saved places and their coordinates, notes, and sharing choices relate to the app, rather than a form on this website.</p><p>A place you search for or select manually is different from your device’s current location. A saved Pin can reveal a location even if device-location permission is off. Check the app’s permission prompts and sharing audience before using location or sharing features. Visiting this website does not grant location permission to the app.</p><p>Information you deliberately make public can be seen and copied by others. People with access to shared content may retain copies after you change its visibility or request deletion. Do not share someone else’s private location without their permission.</p><p>This website does not expose your account or map settings. The beta app’s available controls and notices govern the features you actually use; the illustrations here are not a guarantee of a particular visibility default or continuous-location behavior.</p></section>
    <section id="providers"><h2>Services involved</h2><p>Website hosting and email services process the information needed to deliver pages and messages. Fonts, icons, and illustrations are served with this website; there are no third-party font requests, video embeds, map embeds, or support widgets in its pages.</p><p>The documented app email-confirmation process uses Supabase before directing you here. This website has no Supabase client, database connection, or access to your account. The service sending the confirmation email performs verification.</p><p>Information in support correspondence may need to be shared with service providers to handle the request, or disclosed where applicable law requires it. This website does not include an advertising or data-sale integration.</p></section>
    <section><h2>Retention and security</h2><p>The website does not keep an account database or request submissions. Correspondence and hosting records are separate: relevant retention considerations include resolving your request, operational security, and applicable legal obligations. No fixed deletion or backup-removal period is promised here.</p><p>No method of transmission or storage is completely secure. Keep your sign-in details private. If you suspect unauthorized access, use the <Link href="/support">support guidance</Link>.</p></section>
    <section id="choices"><h2>Your choices and privacy requests</h2><p>Use <Link href="/data-request">Data Requests</Link> for account deletion, deletion of associated personal data, access, correction, or another privacy question. A request is not an immediate deletion. Verification may be necessary before account information can be disclosed or changed.</p><p>Depending on where you live, applicable law may also give you rights to object to or restrict processing, receive a portable copy, withdraw consent where processing relies on it, or complain to a data-protection authority. Explain the right you want to exercise; the outcome depends on the request and applicable law.</p><p>You can manage browser storage through your browser settings and app location permissions through your device settings. Read <Link href="/cookies">Cookies</Link> for the website’s current storage behavior. There is no website newsletter subscription to cancel.</p></section>
    <section><h2>Children and age information</h2><p>This website does not ask for a birth date or age and does not provide a parental-consent process. App eligibility and any age-specific safeguards need to be provided with the beta app. If you are concerned about a child’s information, see <Link href="/data-request">Data Requests</Link>.</p></section>
    <section><h2>Changes and contact</h2><p>We will update this page when the website’s information practices change and show the revision date above. Pins is the product name used on this website.</p><p><ContactDetails subject="Pins privacy question" /></p></section>
  </DocumentPage>;
}
